pg_gsb_frais_home:
    pattern:  /accueil
    defaults: { _controller: PgGsbFraisBundle:Home:index } 
pg_gsb_frais_validerconnexion:
    pattern:  /validerconnexion
    defaults: { _controller: PgGsbFraisBundle:Home:validerconnexion } 
pg_gsb_frais_deconnexion:
    pattern:  /deconnexion
    defaults: { _controller: PgGsbFraisBundle:Home:deconnexion } 
pg_gsb_frais_listefrais:
    pattern:  /listefrais
    defaults: { _controller: PgGsbFraisBundle:ListeFrais:index } 
pg_gsb_frais_saisirfrais:
    pattern:  /saisirfrais
    defaults: { _controller: PgGsbFraisBundle:SaisirFrais:index } 
pg_gsb_frais_validerfraishorsforfais:
    pattern:  /validerfraishorsforfait
    defaults: { _controller: PgGsbFraisBundle:SaisirFrais:validerfraishorsforfait }
pg_gsb_frais_supprimerfraishorsforfait:
    pattern:  /supprimerfraishorsforfait/{id}
    defaults: { _controller: PgGsbFraisBundle:SaisirFrais:supprimerfraishorsforfait }
pg_gsb_frais_listevehicules:
    pattern:  /listevehicules
    defaults: { _controller: PgGsbFraisBundle:ListeVehicules:index } 
pg_gsb_frais_mesvehicules:
    pattern:  /mesvehicules
    defaults: { _controller: PgGsbFraisBundle:ListeVehicules:mesvehicules } 
pg_gsb_frais_ajoutervehicule:
    pattern:  /ajoutervehicule
    defaults: { _controller: PgGsbFraisBundle:Ajoutervehicules:index } 
pg_gsb_frais_supprimervehicule:
    pattern:  /supprimervehicule
    defaults: { _controller: PgGsbFraisBundle:Supprimervehicules:index } 
supprimerlevehicule:
    pattern:  /supprimerlevehicule
    defaults: { _controller: PgGsbFraisBundle:Supprimervehicules:supprimerlevehicule } 
